name: steel_challenge_match_tracker
description: A new Flutter application.

version: 2.2.8+25

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.3.3
  rflutter_alert: ^2.0.7
  url_launcher: ^6.3.1
  sqflite: ^2.4.1
  path_provider: ^2.1.5
  path: ^1.9.0
  just_audio: ^0.9.42
  font_awesome_flutter: ^10.8.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - images/
    - sounds/

