name: steel_challenge_match_tracker
description: A new Flutter application.

version: 2.2.3+16

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
//
  cupertino_icons: ^1.0.3
  shared_preferences: ^2.0.6
  rflutter_alert: ^2.0.4
  url_launcher: ^6.0.9
  sqflite: ^2.0.0+3
  path_provider: ^2.0.2
#  flutter_launcher_icons: ^0.7.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - images/

